export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_FETCH_DATA = 'USER_FETCH_DATA'

export const STREAMS_FETCH_SUCCESS = 'STREAMS_FETCH_SUCCESS'
export const STREAMS_FETCH_PENDING = 'STREAMS_FETCH_PENDING'
export const STREAMS_FETCH_FAILED = 'STREAMS_FETCH_FAILED'